// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmpsghowkyeshctcnwhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcHNnaG93a3llc2hjdGNud2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NDgzODUsImV4cCI6MjA4ODIyNDM4NX0.fu849UDdp4tY8IujFqjYQnFDzbxUcxrmk5rmf24Ndo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});